steps:
  # 🔧 Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Backend
    dir: 'booking-backend'
    args:
      - build
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/clinicbooking/booking-backend:latest'
      - '.'

  # 🚚 Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/clinicbooking/booking-backend:latest'

  # 🚀 Deploy Backend to Cloud Run
  #--set-env-vars=API_URL=${_API_URL} \
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy booking-backend-prod \
          --image=asia-east1-docker.pkg.dev/$PROJECT_ID/clinicbooking/booking-backend:latest \
          --region=asia-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --update-secrets=SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_KEY=SUPABASE_KEY:latest

#substitutions:
# _API_URL: "https://ticketease-frontend-staging-396633212684.asia-east1.run.app/"
#images:
#  - 'gcr.io/$PROJECT_ID/clinicbooking/linebot-backend'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s