steps:
  # 🔨 Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Frontend
    dir: 'booking-frontend'
    args: [
      'build',
      '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/clinicbooking/booking-frontend:${_ENV}',
      '.'
    ]

  # 🚚 Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/clinicbooking/booking-frontend:${_ENV}']

  # 🚀 Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', 'booking-frontend-${_ENV}',
      '--image', 'asia-east1-docker.pkg.dev/$PROJECT_ID/clinicbooking/booking-frontend:${_ENV}',
      '--region', 'asia-east1', '--platform', 'managed',
      '--allow-unauthenticated'
    ]

substitutions:
  _ENV: "staging"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 600s